services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ordbok
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command:
      - "start-dev"
    environment:
#      KC_HOSTNAME: localhost
#      KC_HOSTNAME_PORT: 8080
#      KC_HOSTNAME_STRICT_BACKCHANNEL: false
#      KC_HTTP_ENABLED: true
#      KC_HOSTNAME_STRICT_HTTPS: false
#      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/ordbok
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: 1234
    ports:
      - 9090:8080
#    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network


volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge