spring:
  application:
    name: ordbok
  jpa:
#    database: postgres
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    enabled: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ordbok
    username: admin
    password: 1234
    driverClassName: org.postgresql.Driver
  docker:
    compose:
      enabled: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/ordbok-network
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#      client:
#        registration:
#          ordbok-client:
#            client-id:


